# Site settings
title: Cheng Group @ Soochow University
email: tcheng@suda.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  Stay hungry. Stay foolish.  
  不忘初心，方得始终。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://funsom.suda.edu.cn/tcheng" # the base hostname & protocol for your site
twitter_username: 

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
